package pricing

import (
	"embed"
	"fmt"
	"io/fs"
	"sync"
)

// booksFS holds the built-in price books. They are committed, not fetched, so
// `go build` — and therefore CI, goreleaser, and the distroless image — needs
// no network and the binary prices exactly as well offline as online. That is
// the normal case for this tool, not the error case: it runs in CI and as a
// Helm CronJob, air-gapped from everything but the provider APIs.
//
// books/oci.yaml is regenerated by `just prices` from Oracle's public feed and
// committed; the other three are hand-transcribed, each carrying the URL it
// came from and the date a human last checked it.
//
//go:embed books/*.yaml
var booksFS embed.FS

// defaultDocuments reads the embedded books in a fixed (lexical) order, which
// fs.ReadDir already guarantees. Order is not semantically meaningful — the
// four books share no rate ids or rule types — but a stable order keeps the
// rate card and any merge diagnostics reproducible.
func defaultDocuments() ([]Document, error) {
	entries, err := fs.ReadDir(booksFS, "books")
	if err != nil {
		return nil, fmt.Errorf("pricing: read embedded books: %w", err)
	}
	docs := make([]Document, 0, len(entries))
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		name := "books/" + e.Name()
		data, err := booksFS.ReadFile(name)
		if err != nil {
			return nil, fmt.Errorf("pricing: read %s: %w", name, err)
		}
		docs = append(docs, Document{Name: name, Data: data})
	}
	return docs, nil
}

// defaultBook caches the parse of the embedded books. Load is not expensive,
// but Default is called from the annotator's construction path and the result
// is immutable, so there is no reason to redo it.
var defaultBook = sync.OnceValues(func() (*Book, error) {
	docs, err := defaultDocuments()
	if err != nil {
		return nil, err
	}
	return Load(docs...)
})

// Default returns the embedded price book.
//
// The returned *Book is shared and must not be mutated. Callers wanting to
// layer an override on top go through LoadFile, which reparses from the
// embedded bytes so the shared copy stays pristine.
func Default() (*Book, error) { return defaultBook() }
